version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
      - security
    groups:
      github-actions-breaking:
        update-types:
          - major
      github-actions-backward-compatible:
        update-types:
          - minor
          - patch
