ci/run-unit/@cdktf/cli-core:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/@cdktf/cli-core/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/@cdktf/commons:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/@cdktf/commons/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/@cdktf/hcl2cdk:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/@cdktf/hcl2cdk/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/@cdktf/hcl2json:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/@cdktf/hcl2json/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/@cdktf/provider-generator:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/@cdktf/provider-generator/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/cdktf-cli:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/cdktf-cli/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-unit/cdktf:
  # The workflow used
  - ".github/workflows/unit.yml"
  # All packages under test
  - "packages/cdktf/**"
  # All scripts we use
  - "tools/align-version.sh"

ci/run-examples:
  # The workflow used
  - ".github/workflows/examples.yml"
  # The examples
  - "examples/**"

ci/provider-integration:
  # The workflow used
  - ".github/workflows/provider-integration.yml"
  # The provider generator
  - "packages/@cdktf/provider-generator/**"
  # The tests
  - "test/provider-tests/**"
