shared:
  # sharing this configuration: https://docs.mergify.com/configuration/#shared
  ci: &ci_checks
    # We need to replicate the ignore-paths here as well
    # examples.yml
    - or:
        # Either none of the files are modified
        - -files~=^(examples/|packages/|.terraform.versions.json|package.json)
        # Or we need the check to succeed
        - status-success=examples_success
    # unit.yml
    - or:
        # Either none of the files are modified
        - -files~=^(packages/|.terraform.versions.json|package.json|tools/build-unit-test-matrix.sh)
        # Or we need the check to succeed
        - status-success=unit_tests_success
    # integration.yml
    - or:
        # Either none of the files are modified
        - -files~=^(test/|packages/|.terraform.versions.json|package.json|tools/build-test-matrix.sh)
        # Or we need the checks to succeed
        - and:
            - status-success=linux_integration_success
            - status-success=windows_integration_success
      # provider.yml
    - or:
        # Either none of the files are modified
        - -files~=^(test/provider-tests/|packages/@cdktf/provider-generator/**|package.json|tools/build-provider-test-matrix.sh)
        # Or we need the checks to succeed
        - and:
            - status-success=linux_provider_success
            - status-success=windows_provider_success
  list_of_reviewers: &list_of_reviewers
    - ansgarm
    - DanielMSchmidt
    - mutahhir
  hashi_contributor: &hashi_contributor
    - or:
        - author=ansgarm
        - author=DanielMSchmidt
        - author=Maed223
        - author=mutahhir
        - author=xiehan
  outside_contributor: &outside_contributor
    - author=jsteinich
  core_contributor: &core_contributor
    - or:
        - *hashi_contributor
        - *outside_contributor
  external_contributor: &external_contributor
    - not:
      or:
        - *core_contributor

queue_rules:
  - name: default
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(blocked/do-not-merge )
      - and: *ci_checks
pull_request_rules:
  - name: Trigger CI once the PR
    actions:
      label:
        add: ci/run
    conditions:
      - -conflict
      - or:
          - -draft
          - *external_contributor

  - name: Assign reviewers if CI succeeds
    actions:
      request_reviews:
        users: *list_of_reviewers
        random_count: 1
      label:
        add:
          - ready-for-review
    conditions:
      - -conflict
      - "#approved-reviews-by<1"
      - and: *ci_checks

  - name: Ping on failing CI
    actions:
      label:
        remove:
          - ready-for-review
      comment:
        message: This PR fails CI. Could you fix it @{{author}}? ðŸ™
    conditions:
      - not: *ci_checks
      - and: *hashi_contributor # Restrict to Hashicorp folks for now

  - name: Ping on conflict
    actions:
      label:
        remove:
          - ready-for-review
        add:
          - merge-conflict
      comment:
        message: This PR has merge conflicts. Could you fix it @{{author}}? ðŸ™
    conditions:
      - -draft
      - conflict
      - and: *hashi_contributor # Restrict to Hashicorp folks for now

  - name: Automatic merge on approval and successful build
    actions:
      delete_head_branch: {}
      queue:
        method: rebase
        name: default
    conditions:
      - "#approved-reviews-by>=1"
      - -label~=(blocked/do-not-merge )
      - and: *ci_checks
