pull_request_rules:
  - name: Merge pull requests from dependabot if CI passes
    conditions:
      - author=dependabot[bot]
      - status-success=build
    actions:
      merge:
        method: squash
        commit_message: title+body
        strict: smart
        strict_method: merge
