provider "vsphere" {
  user           = var.vsphere_user
  password       = var.vsphere_password
  vsphere_server = var.vsphere_server
}

resource "vsphere_virtual_machine" "internal-vm" {
  name = "terraform-test"
  // Here we're referencing a provider generated by the
  // base application module that was imported via gradle
  provider = aws.default
}


resource "vsphere_virtual_machine" "external-vm" {
  name     = "terraform-test"
  provider = aws.external
}
