import * as fs from "fs";
import * as os from "os";
import * as path from "path";
import { TerraformProviderGenerator } from "../../generator/provider-generator";
import { CodeMaker } from "codemaker";

test("generates index file that explicitly exports namespaces", async () => {
  const code = new CodeMaker();
  const workdir = fs.mkdtempSync(path.join(os.tmpdir(), "provider.test"));
  const spec = JSON.parse(
    fs.readFileSync(
      path.join(
        __dirname,
        "fixtures",
        "aws-provider-index-file.test.fixture.json"
      ),
      "utf-8"
    )
  );
  new TerraformProviderGenerator(code, spec);
  await code.save(workdir);

  const output = fs.readFileSync(
    path.join(workdir, "providers/aws/index.ts"),
    "utf-8"
  );
  expect(output).toMatchInlineSnapshot(`
    "// generated by cdktf get
    export { CloudFront } from './CloudFront';
    export { ACM } from './ACM';
    export * from './aws-provider';

    "
  `);
});
