export const CUSTOM_DEFAULTS: { [fullName: string]: any } = {
    "aws.security_group.ingress.cidr_blocks": null,
    "aws.security_group.ingress.description": null,
    "aws.security_group.ingress.from_port": null,
    "aws.security_group.ingress.ipv6_cidr_blocks": null,
    "aws.security_group.ingress.prefix_list_ids": null,
    "aws.security_group.ingress.protocol": null,
    "aws.security_group.ingress.security_groups": null,
    "aws.security_group.ingress.self": null,
    "aws.security_group.ingress.to_port": null,
    "aws.security_group.egress.cidr_blocks": null,
    "aws.security_group.egress.description": null,
    "aws.security_group.egress.from_port": null,
    "aws.security_group.egress.ipv6_cidr_blocks": null,
    "aws.security_group.egress.prefix_list_ids": null,
    "aws.security_group.egress.protocol": null,
    "aws.security_group.egress.security_groups": null,
    "aws.security_group.egress.self": null,
    "aws.security_group.egress.to_port": null,
}