const { parse } = require("@cdktf/hcl2json");
const fs = require("fs");
const path = require("path");

// file source: https://github.com/hashicorp/terraform-provider-aws-cloudapi/blob/0c6c2680d2b8c91445737cd30f80f04003ee5665/internal/provider/all_schemas.hcl
const ALL_SCHEMAS_HCL = "all_schemas.hcl";
const OUTPUT_FILE_NAME = "awscc-name-map.ts";

(async function run() {
  const hcl = fs
    .readFileSync(path.resolve(__dirname, ALL_SCHEMAS_HCL))
    .toString();
  const schemas = await parse(ALL_SCHEMAS_HCL, hcl);
  /* schemas (excerpt):
    { "resource_schema":
        {
            "aws_accessanalyzer_analyzer": [{
                "cloudformation_type_name": "AWS::AccessAnalyzer::Analyzer"
            }],
        }
    }
  */

  const { resource_schema } = schemas;
  const entries = Object.entries(resource_schema).map(
    ([tfName, blockContent]) => [
      tfName.replace(/^aws_/, 'awscc_'),
      blockContent[0].cloudformation_type_name,
    ]
  );
  const map = Object.fromEntries(entries);

  fs.writeFileSync(
    path.resolve(__dirname, OUTPUT_FILE_NAME),
    `// this file is generated by schemas.js
export const awsccNameMap = ${JSON.stringify(map)}  
  `
  );
})();
