name: Examples - PR
on:
  merge_group:
    types: [checks_requested]
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  examples:
    name: "Examples Integration Test - PR"
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci/skip-examples') && !contains(github.event.pull_request.labels.*.name, 'ci/unit-only') }}
    uses: ./.github/workflows/examples.yml
    with:
      concurrency_group_prefix: pr
    secrets: inherit
  results:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    name: Result
    needs: [examples]
    steps:
      - run: exit 1
        if: >-
          ${{
               contains(needs.*.result, 'failure')
            || contains(needs.*.result, 'cancelled')
          }}
