name: Examples - PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  examples:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ci/run-examples') || contains(github.event.pull_request.labels.*.name, 'ci/run-all') }}
    uses: ./.github/workflows/examples.yml
    with:
      concurrency_group_prefix: pr
    secrets: inherit
