name: Integration Tests - PR
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - labeled
      - unlabeled
      - reopened

jobs:
  integration_test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'ci/skip-integration') && !contains(github.event.pull_request.labels.*.name, 'ci/unit-only') }}
    uses: ./.github/workflows/integration.yml
    with:
      concurrency_group_prefix: pr
    secrets: inherit
