name: PR Size label

on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    name: Label the PR size
    steps:
      - uses: codelytv/pr-size-labeler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          xs_label: "size/xs"
          xs_max_size: "10"
          s_label: "size/s"
          s_max_size: "100"
          m_label: "size/m"
          m_max_size: "500"
          l_label: "size/l"
          l_max_size: "1000"
          xl_label: "size/xl"
          fail_if_xl: "false"
          message_if_xl: >
            This PR exceeds the recommended size of 1000 lines.
            Please make sure you are NOT addressing multiple issues with one PR.
            Note this PR might be rejected due to its size.
          # Ignoring generate files
          files_to_ignore: "website/docs/cdktf/api-reference/csharp.mdx website/docs/cdktf/api-reference/go.mdx website/docs/cdktf/api-reference/java.mdx website/docs/cdktf/api-reference/python.mdx website/docs/cdktf/api-reference/typescript.mdx"
