name: Unit Tests - @cdktf/hcl2json
on:
  pull_request:
    paths:
      # This workflow
      - ".github/workflows/unit-@cdktf-hcl2json.yml"
      # All packages under test
      - "packages/@cdktf/hcl2json/**"
      # All scripts we use
      - "tools/build-unit-test-matrix.sh"
      - "tools/align-version.sh"

jobs:
  unit_test:
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version: ["1.2.8"]
    with:
      concurrency_group_prefix: release
      package: "@cdktf/hcl2json"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit
