name: Unit Tests - cdktf
on:
  pull_request:
    paths:
      # This workflow
      - ".github/workflows/unit-cdktf.yml"
      # All packages under test
      - "packages/cdktf/**"
      # All scripts we use
      - "tools/build-unit-test-matrix.sh"
      - "tools/align-version.sh"

jobs:
  unit_test:
    needs:
      - prepare-release
    uses: ./.github/workflows/unit.yml
    strategy:
      fail-fast: false
      matrix:
        terraform_version:
          - "1.2.8"
    with:
      concurrency_group_prefix: release
      package: "cdktf"
      terraform_version: ${{ matrix.terraform_version }}
    secrets: inherit
